import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { BrowserRouter, useNavigate } from "react-router-dom";
import { Activity, Bot, Building2, Check, ChevronRight, CircleUserRound, LayoutDashboard, LogOut, Package, Plus, RefreshCw, Server, Settings2, ShieldCheck, Store, Users, X } from "lucide-react";
import "@/App.css";

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const api = axios.create({ baseURL: API, withCredentials: true });
const money = (value) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0);

function App() { return <BrowserRouter><Panel /></BrowserRouter>; }

function Panel() {
  const nav = useNavigate();
  const [user, setUser] = useState(null); const [loading, setLoading] = useState(true); const [page, setPage] = useState("overview");
  const [stores, setStores] = useState([]); const [plans, setPlans] = useState([]); const [selected, setSelected] = useState(null); const [notice, setNotice] = useState("");
  const [login, setLogin] = useState({ email: "admin@zappedidos.com", senha: "Zap@2026" }); const [newStore, setNewStore] = useState({ nome: "", cliente_email: "", cliente_senha: "", plano: "Essencial" });
  const [product, setProduct] = useState({ nome: "", descricao: "", preco: "", categoria: "Geral" }); const [waha, setWaha] = useState({ base_url: "", api_token: "", session_name: "" }); const [wahaState, setWahaState] = useState(null);
  const isStaff = user && ["admin", "reseller"].includes(user.role);
  const selectedStore = stores.find((item) => item.id === selected) || stores[0];

  async function load() { try { const me = await api.get("/auth/me"); setUser(me.data); const data = await api.get("/dashboard"); setStores(data.data.lojas); setPlans((await api.get("/plans")).data); } catch { setUser(false); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  useEffect(() => { if (selectedStore && page === "connection") api.get(`/stores/${selectedStore.id}/waha`).then((r) => setWahaState(r.data)); }, [selectedStore, page]);
  async function signIn(e) { e.preventDefault(); try { const r = await api.post("/auth/login", login); setUser(r.data); setNotice("Login realizado com sucesso"); load(); } catch { setNotice("Não foi possível entrar. Verifique os dados."); } }
  async function signOut() { await api.post("/auth/logout"); setNotice(""); setUser(false); }
  async function addStore(e) { e.preventDefault(); try { await api.post("/stores", newStore); setNewStore({ nome: "", cliente_email: "", cliente_senha: "", plano: "Essencial" }); setNotice("Loja e acesso do cliente criados"); load(); } catch (error) { setNotice(error.response?.data?.detail || "Revise os dados da loja"); } }
  async function addProduct(e) { e.preventDefault(); await api.post(`/stores/${selectedStore.id}/products`, { ...product, preco: Number(product.preco) }); setProduct({ nome: "", descricao: "", preco: "", categoria: "Geral" }); setNotice("Produto salvo no catálogo"); }
  async function setupWaha(e) { e.preventDefault(); try { const r = await api.post(`/stores/${selectedStore.id}/waha/setup`, waha); setWahaState(r.data); setNotice(r.data.message); } catch { setNotice("Não foi possível salvar a conexão WAHA"); } }
  if (loading) return <div className="loading-screen">Carregando seu painel<span>●</span></div>;
  if (!user) return <Login login={login} setLogin={setLogin} signIn={signIn} notice={notice} />;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Bot size={19} /></span><div><strong>ZapPedidos</strong><small>Control center</small></div></div><div className="workspace-label">{isStaff ? "OPERAÇÃO" : "MINHA LOJA"}</div><nav>{[["overview", LayoutDashboard, isStaff ? "Visão geral" : "Meu painel"], ...(isStaff ? [["stores", Building2, "Lojas e clientes"], ["plans", ShieldCheck, "Planos"]] : []), ["catalog", Package, "Catálogo"], ["connection", Server, "WhatsApp / Waha"], ["settings", Settings2, "Configurações"]].map(([key, Icon, label]) => <button key={key} className={page === key ? "nav-item active" : "nav-item"} onClick={() => setPage(key)} data-testid={`nav-${key}`}><Icon size={17} />{label}{key === "connection" && selectedStore?.waha_status === "connected" && <i className="dot" />}</button>)}</nav><div className="sidebar-bottom"><div className="account-mini"><CircleUserRound size={25} /><div><strong>{user.nome}</strong><small>{user.role === "admin" ? "Administrador geral" : user.role === "reseller" ? "Revendedor" : "Cliente"}</small></div></div><button className="logout" onClick={signOut} data-testid="logout-button"><LogOut size={16} />Sair</button></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">{isStaff ? "PAINEL ADMINISTRATIVO" : "ÁREA DO CLIENTE"}</span><h1>{page === "overview" ? "Bom dia, " + (user.nome?.split(" ")[0] || "equipe") : pageTitle(page)}</h1></div><div className="top-actions">{selectedStore && <select value={selectedStore.id} onChange={(e) => setSelected(e.target.value)} data-testid="store-selector"><option value="">Selecione uma loja</option>{stores.map((s) => <option key={s.id} value={s.id}>{s.nome}</option>)}</select>}<span className="live"><i /> Sistema online</span></div></header>{notice && <div className="notice" data-testid="notice"><Check size={16} />{notice}<button onClick={() => setNotice("")}><X size={15} /></button></div>}{page === "overview" && <Overview stores={stores} user={user} setPage={setPage} setSelected={setSelected} />}{page === "stores" && <Stores stores={stores} setSelected={setSelected} setPage={setPage} newStore={newStore} setNewStore={setNewStore} addStore={addStore} />}{page === "plans" && <Plans plans={plans} stores={stores} />}{page === "catalog" && <Catalog store={selectedStore} product={product} setProduct={setProduct} addProduct={addProduct} />}{page === "connection" && <Connection store={selectedStore} waha={waha} setWaha={setWaha} setupWaha={setupWaha} state={wahaState} refresh={() => api.post(`/stores/${selectedStore.id}/waha/test`).then((r) => setWahaState(r.data))} />}{page === "settings" && <Settings user={user} store={selectedStore} />}</main></div>;
}

function Login({ login, setLogin, signIn, notice }) { return <div className="login-page"><div className="login-art"><div className="brand"><span className="brand-mark"><Bot size={19} /></span><div><strong>ZapPedidos</strong><small>Reseller workspace</small></div></div><div className="art-copy"><span className="eyebrow">AUTOMAÇÃO PARA DELIVERY</span><h1>Seu WhatsApp,<br /><em>sob controle.</em></h1><p>Uma operação inteira para você conectar clientes, acompanhar lojas e fazer cada pedido avançar.</p><div className="art-proof"><span><Activity size={16} /> Status em tempo real</span><span><ShieldCheck size={16} /> Multi-tenant seguro</span></div></div></div><form className="login-form" onSubmit={signIn}><div className="form-kicker">ACESSO RESTRITO</div><h2>Entrar no painel</h2><p className="muted">Use suas credenciais para continuar.</p><label>E-mail<input type="email" value={login.email} onChange={(e) => setLogin({ ...login, email: e.target.value })} data-testid="login-email-input" /></label><label>Senha<input type="password" value={login.senha} onChange={(e) => setLogin({ ...login, senha: e.target.value })} data-testid="login-password-input" /></label>{notice && <div className="error">{notice}</div>}<button className="primary wide" type="submit" data-testid="login-submit-button">Entrar no workspace <ChevronRight size={17} /></button><small className="login-hint">Administrador inicial: admin@zappedidos.com</small></form></div>; }
function Overview({ stores, user, setPage, setSelected }) { const connected = stores.filter((s) => s.waha_status === "connected").length; return <><section className="hero"><div><span className="eyebrow">{new Date().toLocaleDateString("pt-BR", { weekday: "long", day: "2-digit", month: "long" })}</span><h2>Uma visão clara da<br /><em>sua operação.</em></h2><p>Gerencie conexões, lojas e o catálogo dos seus clientes em um só lugar.</p></div><div className="hero-signal"><div className="signal-ring"><Bot size={27} /></div><strong>WAHA CORE</strong><span>Infraestrutura pronta</span></div></section><div className="metrics"><Metric label="Lojas ativas" value={stores.length} detail="clientes na base" icon={Building2} /><Metric label="WhatsApp conectado" value={connected} detail={`de ${stores.length} instâncias`} icon={Activity} accent="green" /><Metric label="Planos em uso" value={new Set(stores.map((s) => s.plano)).size} detail="configurações ativas" icon={ShieldCheck} accent="amber" /><Metric label="Bot em operação" value={stores.filter((s) => s.bot_ativo).length} detail="atendentes ligados" icon={Bot} accent="blue" /></div><div className="section-head"><div><span className="eyebrow">CENTRAL DE OPERAÇÃO</span><h3>{user.role === "client" ? "Sua loja" : "Lojas recentes"}</h3></div>{user.role !== "client" && <button className="ghost" onClick={() => setPage("stores")} data-testid="manage-stores-button">Ver todas <ChevronRight size={15} /></button>}</div><div className="store-grid">{stores.slice(0, 4).map((store) => <StoreCard key={store.id} store={store} open={() => { setSelected(store.id); setPage("connection"); }} />)}{!stores.length && <div className="empty">Nenhuma loja cadastrada ainda. Abra “Lojas e clientes” para começar.</div>}</div></>; }
function Metric({ label, value, detail, icon: Icon, accent = "" }) { return <div className="metric" data-testid={`metric-${label.toLowerCase().replaceAll(" ", "-")}`}><div className={`metric-icon ${accent}`}><Icon size={18} /></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>; }
function StoreCard({ store, open }) { return <button className="store-card" onClick={open} data-testid={`store-card-${store.id}`}><div className="store-card-top"><span className="store-avatar"><Store size={18} /></span><span className={store.waha_status === "connected" ? "status connected" : "status pending"}><i />{store.waha_status === "connected" ? "Conectado" : store.waha_status === "not_configured" ? "Configurar" : "Aguardando"}</span></div><strong>{store.nome}</strong><span className="store-email">{store.cliente_email}</span><div className="store-card-bottom"><span>{store.plano}</span><ChevronRight size={15} /></div></button>; }
function Stores({ stores, setSelected, setPage, newStore, setNewStore, addStore }) { return <><div className="section-head"><div><span className="eyebrow">BASE DE CLIENTES</span><h2>Lojas e clientes</h2></div><span className="count-pill">{stores.length} lojas</span></div><div className="content-grid"><div className="panel"><div className="panel-head"><div><h3>Adicionar uma loja</h3><p>Crie a loja e o acesso do cliente em uma única etapa.</p></div><Plus size={19} /></div><form className="stack-form" onSubmit={addStore}><label>Nome da loja<input required value={newStore.nome} onChange={(e) => setNewStore({ ...newStore, nome: e.target.value })} placeholder="Ex.: Ponto do Açaí" data-testid="store-name-input" /></label><label>E-mail do cliente<input required type="email" value={newStore.cliente_email} onChange={(e) => setNewStore({ ...newStore, cliente_email: e.target.value })} placeholder="cliente@empresa.com" data-testid="client-email-input" /></label><div className="two-cols"><label>Senha inicial<input type="password" required value={newStore.cliente_senha} onChange={(e) => setNewStore({ ...newStore, cliente_senha: e.target.value })} data-testid="client-password-input" /></label><label>Plano<select value={newStore.plano} onChange={(e) => setNewStore({ ...newStore, plano: e.target.value })} data-testid="plan-select"><option>Essencial</option><option>Crescimento</option><option>Escala</option></select></label></div><button className="primary" type="submit" data-testid="create-store-button">Criar loja <Plus size={16} /></button></form></div><div className="panel"><div className="panel-head"><div><h3>Clientes cadastrados</h3><p>Selecione uma loja para configurar sua conexão.</p></div><Users size={19} /></div><div className="client-list">{stores.map((s) => <button key={s.id} className="client-row" onClick={() => { setSelected(s.id); setPage("connection"); }} data-testid={`client-row-${s.id}`}><span className="store-avatar small"><Store size={15} /></span><span><strong>{s.nome}</strong><small>{s.cliente_email}</small></span><span className="row-plan">{s.plano}</span><ChevronRight size={15} /></button>)}</div></div></div></>; }
function Plans({ plans, stores }) { return <><div className="section-head"><div><span className="eyebrow">MODELO COMERCIAL</span><h2>Planos de revenda</h2></div></div><div className="plans-grid">{plans.map((plan) => <div className="plan-card" key={plan.id}><span className={`plan-dot ${plan.cor}`} /><h3>{plan.nome}</h3><strong>{money(plan.preco)}<small>/mês</small></strong><p>Até {plan.limite_lojas > 900 ? "lojas ilimitadas" : `${plan.limite_lojas} lojas`} por cliente</p><div className="plan-used"><span>Em uso</span><b>{stores.filter((s) => s.plano === plan.nome).length}</b></div></div>)}</div></>; }
function Catalog({ store, product, setProduct, addProduct }) { const [items, setItems] = useState([]); useEffect(() => { if (store) api.get(`/stores/${store.id}/products`).then((r) => setItems(r.data)); }, [store]); if (!store) return <EmptySelect />; return <><div className="section-head"><div><span className="eyebrow">CARDÁPIO DIGITAL · {store.nome}</span><h2>Catálogo de produtos</h2></div><span className="count-pill">{items.length} itens</span></div><div className="content-grid"><div className="panel"><div className="panel-head"><div><h3>Novo produto</h3><p>O bot usa estes itens para montar pedidos.</p></div><Package size={19} /></div><form className="stack-form" onSubmit={async (e) => { await addProduct(e); const r = await api.get(`/stores/${store.id}/products`); setItems(r.data); }}><label>Nome<input required value={product.nome} onChange={(e) => setProduct({ ...product, nome: e.target.value })} placeholder="Ex.: X-Bacon" data-testid="product-name-input" /></label><label>Descrição<input value={product.descricao} onChange={(e) => setProduct({ ...product, descricao: e.target.value })} placeholder="Ingredientes e detalhes" data-testid="product-description-input" /></label><div className="two-cols"><label>Preço<input required type="number" step="0.01" value={product.preco} onChange={(e) => setProduct({ ...product, preco: e.target.value })} placeholder="0,00" data-testid="product-price-input" /></label><label>Categoria<input value={product.categoria} onChange={(e) => setProduct({ ...product, categoria: e.target.value })} data-testid="product-category-input" /></label></div><button className="primary" type="submit" data-testid="create-product-button">Adicionar produto <Plus size={16} /></button></form></div><div className="panel"><div className="panel-head"><div><h3>Itens ativos</h3><p>Visíveis para o atendimento automático.</p></div></div><div className="product-list">{items.map((item) => <div className="product-row" key={item.id}><span className="product-icon"><Package size={16} /></span><span><strong>{item.nome}</strong><small>{item.categoria} · {item.descricao || "Sem descrição"}</small></span><b>{money(item.preco)}</b></div>)}{!items.length && <div className="empty compact">Nenhum produto cadastrado.</div>}</div></div></div></>; }
function Connection({ store, waha, setWaha, setupWaha, state, refresh }) { if (!store) return <EmptySelect />; const status = state?.status || store.waha_status; return <><div className="section-head"><div><span className="eyebrow">CONEXÃO POR CLIENTE · {store.nome}</span><h2>WhatsApp / Waha</h2></div><span className={`status large ${status === "connected" ? "connected" : "pending"}`}><i />{status === "connected" ? "Conectado" : status === "not_configured" ? "Não configurado" : "Ação necessária"}</span></div><div className="connection-layout"><div className="connection-main"><div className="connection-visual"><div className="qr-placeholder"><Server size={34} /><span>{status === "connected" ? "Sessão ativa" : "QR Code"}</span><small>{status === "connected" ? "WhatsApp conectado ao bot" : "O QR aparecerá após iniciar a sessão"}</small></div><div><span className="eyebrow">INSTÂNCIA EXCLUSIVA</span><h3>{state?.session_name || store.waha_session || `zp_${store.id.slice(0, 10)}`}</h3><p>Cada cliente possui sua própria sessão, token e webhook. Nenhuma configuração é compartilhada entre lojas.</p><button className="ghost" onClick={refresh} data-testid="refresh-waha-button"><RefreshCw size={15} /> Atualizar status</button></div></div></div><div className="panel connection-form"><div className="panel-head"><div><h3>Configurar instância</h3><p>Informe os dados do WAHA instalado na sua VPS.</p></div><Server size={19} /></div><form className="stack-form" onSubmit={setupWaha}><label>URL da instância<input required value={waha.base_url} onChange={(e) => setWaha({ ...waha, base_url: e.target.value })} placeholder="https://waha.seudominio.com" data-testid="waha-url-input" /></label><label>Token da API<input required type="password" value={waha.api_token} onChange={(e) => setWaha({ ...waha, api_token: e.target.value })} placeholder="Token fornecido pelo WAHA" data-testid="waha-token-input" /></label><label>Nome da sessão <span className="optional">opcional</span><input value={waha.session_name} onChange={(e) => setWaha({ ...waha, session_name: e.target.value })} placeholder={`zp_${store.id.slice(0, 8)}`} data-testid="waha-session-input" /></label><button className="primary" type="submit" data-testid="save-waha-button">Salvar e iniciar sessão <ChevronRight size={16} /></button></form></div></div></>; }
function Settings({ user, store }) { return <div className="settings-wrap"><span className="eyebrow">PREFERÊNCIAS</span><h2>Configurações</h2><div className="panel settings-card"><div className="account-row"><span className="store-avatar"><CircleUserRound size={19} /></span><div><strong>{user.nome}</strong><small>{user.email}</small></div><span className="row-plan">{user.role}</span></div>{store && <div className="setting-line"><span><strong>Bot ativo</strong><small>{store.nome} responde automaticamente pelo WhatsApp</small></span><span className="toggle on"><i /></span></div>}<div className="setting-line"><span><strong>Ambiente da operação</strong><small>Todos os dados ficam isolados por cliente</small></span><span className="secure"><ShieldCheck size={15} /> Seguro</span></div></div></div>; }
function EmptySelect() { return <div className="empty-select"><Store size={30} /><h2>Selecione uma loja</h2><p>Escolha uma loja no seletor acima para continuar.</p></div>; }
function pageTitle(page) { return { stores: "Lojas e clientes", plans: "Planos de revenda", catalog: "Catálogo", connection: "WhatsApp / Waha", settings: "Configurações" }[page]; }
export default App;